fix(tests): Add missing arena and workqueue dependencies to consolidation tests
Link test_consolidate_incremental_delta and test_consolidate_kway_merge
against wirelog arena and workqueue libraries to resolve undefined
reference errors when building with LTO (Link-Time Optimization) on clang.

Fixes linker errors:
- undefined reference to 'wl_arena_create'
- undefined reference to 'wl_arena_free'
- undefined reference to 'wl_arena_reset'
- undefined reference to 'wl_workqueue_create'
- undefined reference to 'wl_workqueue_submit'
- undefined reference to 'wl_workqueue_wait_all'
- undefined reference to 'wl_workqueue_drain'
- undefined reference to 'wl_workqueue_destroy'